### ISSUE TITLE
不支持eslint^3.0.0

### ISSUE THREAD

**Issue by lili21** [ElemeFE/eslint-config-elemefe#4]
[new rule format](http://eslint.org/blog/2016/07/eslint-new-rule-format)

**Comment by furybean** [comment]
Okay，@QingWei-Li 有空处理下。

**Comment by QingWei-Li** [comment]
。。。。。。。居然就出到了 3

**Comment by QingWei-Li** [comment]
@lili21 我看了下 似乎并不影响现有的配置呀

**Comment by lili21** [comment]
@QingWei-Li 我升到3.0.0上，并没有效果，没有任何错误提示

**Comment by QingWei-Li** [comment]
@lili21 麻烦给个例子
我刚才用 vue-cli 创建的项目，然后 `.eslintrc` 配置成下面这样，并使用 eslint@3.0.1 一切正常。写错的地方会有提示。

``` json
{
  "plugins": ["html"],
  "extends": ["elemefe"]
}
```

**Comment by CodeBoy-Jun** [comment]
table控件的多选按钮能根据业务规则控制是否出现吗？
